/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ea75e688-2151-4960-b135-c13ac257abc2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_4GTiGrknO",
    "aws_user_pools_web_client_id": "f9iabtjcit37es9up3vrtqvd",
    "oauth": {}
};


export default awsmobile;
